os:
  - osx
language: swift
osx_image: xcode8
script:
  - xcodebuild -enableCodeCoverage YES  -scheme StateTransition-tvOS -project StateTransition.xcodeproj -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - xcodebuild -scheme StateTransition-macOS -project StateTransition.xcodeproj build test
  - xcodebuild -scheme StateTransition-watchOS -project StateTransition.xcodeproj build
  - gem install cocoapods
  - pod repo update --silent
  - pod lib lint --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)